variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PAGES_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_COMMIT_REF_SLUG/storybook/'
  PAGES_MAIN_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_DEFAULT_BRANCH/storybook/'
  DOCKER_NODE_IMAGE: docker-registry.esrf.fr/dau/node:14.18.2
stages:
  - test
  - build
  - deployment


pages:
  stage: build
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run build-storybook
    - ls && cp -r storybook-static public && ls && ls public
    - mv mkdocs-doc public
  artifacts:
    paths:
      - public

Build-doc:
  stage: build
  image: python:latest
  script:
    - pip install mkdocs-material &&  pip install mkdocstrings
    - cd documentation && mkdocs build --site-dir mkdocs-doc
  artifacts:
    paths:
      - mkdocs-doc

Build-App:
  stage: build
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run build

Flow:
  stage: test
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run lint

Lint:
  stage: test
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run lint
