variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PAGES_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_COMMIT_REF_SLUG/storybook/'
  PAGES_MAIN_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_DEFAULT_BRANCH/storybook/'

stages:
  - test
  - build
  - deployment

Build-Storybook:
  stage: build
  image: node:14.18.2
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - storybook-static
  script:
    - npm ci
    - npm run build-storybook
    - cp -r storybook-static public/storybook && ls && ls public

Deploy-Storybook:
  stage: deployment
  script:
    - echo "This job configures an environment."
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: $PAGES_URL
    #on_stop: remove-storybook

Build-Pages:
  stage: build
  image: python:latest
  script:
    - pip install mkdocs-material &&  pip install mkdocstrings
    - cd documentation && mkdocs build --site-dir ../public/documentation && cd.. && ls && ls public
  artifacts:
    paths:
      - public/documentation
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

Build-App:
  stage: build
  image: node:14.18.2
  script:
    - npm ci
    - npm run build

Flow:
  stage: test
  image: node:14.18.2
  script:
    - npm ci
    - npm run lint

Lint:
  stage: test
  image: node:14.18.2
  script:
    - npm ci
    - npm run lint

.docker-template:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
