variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PAGES_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_COMMIT_REF_SLUG/storybook/'
  PAGES_MAIN_URL: 'https://ispyb.gitlab-pages.esrf.fr/py-ispyb-ui/$CI_DEFAULT_BRANCH/storybook/'
  DOCKER_NODE_IMAGE: docker-registry.esrf.fr/dau/node:14.18.2
stages:
  - test
  - build
  - deployment

Build-Storybook:
  stage: build
  image: $DOCKER_NODE_IMAGE
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - storybook
  script:
    - npm ci
    - npm run build-storybook --output-dir storybook

Deploy-Storybook:
  stage: deployment
  script:
    - echo "This job configures an environment."
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: $PAGES_URL
    #on_stop: remove-storybook

pages:
  stage: deployment
  image: python:latest
  script:
    - pip install mkdocs-material &&  pip install mkdocstrings
    - cd documentation && mkdocs build --site-dir ../public
    - ls  && cp -r ../storybook ../public/storybook && ls && ls public
  artifacts:
    paths:
      - public

Build-App:
  stage: build
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run build

Flow:
  stage: test
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run lint

Lint:
  stage: test
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run lint
