variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - test
  - documentation

pages:
  stage: documentation
  image: python:latest
  script:
    - pip install mkdocs-material &&  pip install mkdocstrings
    - cd documentation && mkdocs build --site-dir ../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

Lint:
  stage: test
  image: node:14.18.2
  script:
    - npm ci
    - npm run lint

.docker-template:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
